### ISSUE TITLE
Design Documents

### ISSUE THREAD

**Issue by MisterC-Rogers** [quinwoods/catalystchildcare.org#1]
We need design documents to settle on the design and flow of the website

**Comment by quinwoods** [comment]
Agreed, the current logo is: 
![Logo](https://user-images.githubusercontent.com/44750253/174312212-d6e7877a-0671-4501-b68b-c97d77a78a84.png)
This can change at any moment but the colors that we would like to keep consistent are:
**Primary-Gradient**: 
- Indigo 
- Blue
**Secondary**: 
- Red 
- Yellow 
- Orango 
- Green 
- Blue

I do not currently have the text that should be going on the site but for now I will put some filler words so we can get the general shape of the site.

**Comment by quinwoods** [comment]
![CleanShot 2022-06-19 at 00 05 26@2x](https://user-images.githubusercontent.com/44750253/174465366-f332bc1f-e8f0-45c6-b46a-ddf42de22380.png)

**Comment by quinwoods** [comment]
Closing because all parties now understand the design flow of the website and we are past the mock up stage.
