### ISSUE TITLE
Replace social buttons with TOS & PP

### ISSUE THREAD

**Issue by JamesSedlacek** [quinwoods/catalystchildcare.org#5]
Remove the Instagram..etc. buttons at the bottom of the page and replace with Terms of Service & Privacy Policy buttons with links to their pages

**Comment by dorian-edwards** [comment]
Hey James, do you have a link to the terms of service and privacy policy, I'm having trouble finding it.

**Comment by JamesSedlacek** [comment]
We need to create the pages for those. Just use placeholder text for now (for the actual content for those pages).

**Comment by JDouglasR** [comment]
Issue partially resolved in pending merge from PR -- Added the ToS and PP but did not remove social icons as I was unsure of my authority to remove

**Comment by quinwoods** [comment]
@JDouglasR 
Remove away dude!

**Comment by dorian-edwards** [comment]
No worries I got it.

**Comment by JDouglasR** [comment]
Appreciate it, i work till 5.30est so if you can't get to it I can take care of it later

**Comment by dorian-edwards** [comment]
This issue has been resolved in PR #16
